print("Hello World")
print("Data Science at Moringa")
print ("Mukuhi Mukundi")
print("please work")
print("Different")
print("I cant wait")
print("not why")
print( "it Worked")
print("why")
print("Really")
